### PR TITLE
WIP: Manual traits

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/683

First commit is regen from latest gir-files without manual trait

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
.. so better look only second commit.

**Comment by EPashkin** [comment]
Updated with parent manual traits (still current crate only). 2 other PRs updated too.

**Comment by EPashkin** [comment]
Updated with latest manual traits, still WIP

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege 
Updated all gtk-rs crates with gir-files from Ubintu-disco (and wrongly used link to this PR instead https://github.com/gtk-rs/gir-files/pull/32).
Them ready for check.
Canceled all CI except sys

**Comment by EPashkin** [comment]
Tried to regen with new gir-files, but cargo doc done only one change in pangocairo.
See third commit

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
:+1:

**Pull request merged**
