### PR TITLE
Remove totally deprecated docs

### PR DESCRIPTION
**Pull request by EPashkin**
Followup #54 
Part of https://github.com/gtk-rs/gir/pull/744

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Let's wait for the gir PR to be merged first if you don't mind. Then I'll merge this one.

**Comment by EPashkin** [comment]
Agree that better wait for both gir and gtk PR's

**Comment by GuillaumeGomez** [comment]
Is there anything to update in here or can I merge it?

**Comment by EPashkin** [comment]
Yes, this ready for merge, thanks for reminder.

**Comment by GuillaumeGomez** [comment]
Thanks then! ;)

**Pull request merged**
