### PR TITLE
Add manual docs for StyleContextl::get_font

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/issues/949

Prepare doc for manual implemented function

cc  @GuillaumeGomez , @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! Just waiting for CI before merging.

**Comment by EPashkin** [comment]
CI passed

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege 
https://github.com/gtk-rs/gtk/pull/953 already merged only docs last

**Comment by GuillaumeGomez** [comment]
Sorry, forgot about it. ><

Thanks again!

**Pull request merged**
