### PR TITLE
Regen vendor docs

### PR DESCRIPTION
**Pull request by EPashkin**
cc @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
Maybe others generated (gio, glib, pange) need `vendor.md` too (with features)?

**Comment by GuillaumeGomez** [comment]
I suppose yes. Do you want to update them in this PR as well?

**Comment by EPashkin** [comment]
Yes

**Comment by GuillaumeGomez** [comment]
Just ping me once done then. (And thanks!)

**Comment by EPashkin** [comment]
Updated docs.
Include manual docs for glib (it works not good, so maybe glib need empty purge pass or works only to `src/auto`).
Crate publish need wait for #30.
@GuillaumeGomez please add tags for already published versions of https://crates.io/crates/gtk-rs-lgpl-docs.

**Comment by GuillaumeGomez** [comment]
What tags are you talking about?

**Comment by EPashkin** [comment]
"v0.1.3" etc. to git.

**Comment by GuillaumeGomez** [comment]
And done: https://github.com/gtk-rs/lgpl-docs/releases

**Comment by EPashkin** [comment]
Thanks

**Comment by EPashkin** [comment]
IMHO only tags was needed as releases stored at crates.io

**Comment by GuillaumeGomez** [comment]
Isn't it what I did?

**Comment by EPashkin** [comment]
My mistake, I did not know that github automatically create release for tags.

**Comment by GuillaumeGomez** [comment]
github's dark magic. ;)

Is it ready to merge or do you want to do something else?

**Comment by EPashkin** [comment]
Still not sure, if `glib` need `docs.md` or we will make only `src/auto` processed.
Besides that, all ready.

**Comment by GuillaumeGomez** [comment]
Let's merge for now then. Thanks!

**Pull request merged**
