### PR TITLE
Support overriding vendor docs with gtk-rs-specific ones

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
All good for me.

**Comment by gkoz** [comment]
Meh, the tests fail because the examples repo already expects the changes from https://github.com/gtk-rs/gtk/pull/288.

**Comment by gkoz** [comment]
Oh and we should release the latest rustdoc-stripper to crates and update the dependency here.

**Comment by GuillaumeGomez** [comment]
@gkoz: rustdoc-stripper new crate verson has been pushed to crates.io (the [PR](https://github.com/GuillaumeGomez/rustdoc-stripper/pull/43) is here).

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
