### PR TITLE
Add pangocairo docs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Only minor problem that it don't have `pango_cairo_context_get_font_options` and other function
https://github.com/gtk-rs/sys/blob/master/pangocairo-sys/src/lib.rs#L67-L85
But https://github.com/gtk-rs/pangocairo also don't contains this.

**Comment by GuillaumeGomez** [comment]
Yes, it's a bit weird.

**Comment by EPashkin** [comment]
Forgot about that, you need add this to pangocairo's `Gir.toml` to generate functions.
```
[[object]]
name = "PangoCairo.*"
status = "generate"
```

**Comment by EPashkin** [comment]
* I forgot about that, ...

**Comment by GuillaumeGomez** [comment]
Oh damn...

**Comment by GuillaumeGomez** [comment]
More code generated but no more docs. Strange. I'll merge this for now then.

**Pull request merged**
