### PR TITLE
Regenerate and change version format

### PR DESCRIPTION
**Pull request by gkoz**
The new crate version would need to be published then.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Sure, I wait for travis then I publish it. Thanks!

**Comment by gkoz** [comment]
The 'travis-ci/push' status is failing because I had misplaced a branch, 'travis-ci/pr' is the correct one.

**Comment by GuillaumeGomez** [comment]
I published it.

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
