### PR TITLE
Add graphene, gdk4, gsk4, gtk4

### PR DESCRIPTION
**Pull request by sfanxiang**
Currently no manual doc. It's required for CI to pass.

cc @sdroege @GuillaumeGomez

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
👍

**Comment by sfanxiang** [comment]
@sdroege Could you merge it if it's good? Or are we waiting for anything?

**Comment by sdroege** [comment]
> @sdroege Could you merge it if it's good? Or are we waiting for anything?

I don't have the permissions to do that, only @GuillaumeGomez does

**Comment by GuillaumeGomez** [comment]
I am the master of the docs. :rofl: 

Thanks!

**Pull request merged**
