### PR TITLE
Update documentation for cairo

### PR DESCRIPTION
**Pull request by meh**
I'm pretty sure I did this wrong 🐼 

Should I fix this by hand?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
The output seems a bit weird. :full_moon:

**Comment by meh** [comment]
It is weird, I run `rustdoc-stripper` without any arguments in the project root, but the diff looks easy enough to fix by hand.

**Comment by GuillaumeGomez** [comment]
What's really weird is that a lot of lines are deleted. Have you generated back the docs before stripping them?

**Comment by meh** [comment]
Yeah, I did, I'll try fixing it by hand because not everything is gone.

**Comment by EPashkin** [comment]
@GuillaumeGomez there was long unused enums, maybe it generated for sys part. Not sure what better remove it now, or just add meh's part.

**Comment by meh** [comment]
Should be fine now.

**Comment by GuillaumeGomez** [comment]
Seems good to me. :)

**Comment by EPashkin** [comment]
Also

**Comment by GuillaumeGomez** [comment]
Then let's merge. Thanks @meh!

**Comment by GuillaumeGomez** [comment]
(Just waiting for CI just in case...)

**Comment by EPashkin** [comment]
Part of https://github.com/gtk-rs/cairo/pull/165.

**Pull request merged**
